### PR TITLE
Support Swift 2.3

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ishkawa** [comment]
Thank you for the PR 👍 

It seems that OHHTTPStubs needs project global deployment target for iOS and tvOS because APIKitTests will be built for these OSs. On master branch, APIKitTests uses OHHTTPStubs customized by following commits:

- https://github.com/ishkawa/OHHTTPStubs/commit/c7e2211e24e937fc6b6883bdfc354d488db5208c
- https://github.com/ishkawa/OHHTTPStubs/commit/75f74c9c19620a37f436b38e2bc20a07310b999e

**Comment by ikesyo** [comment]
Oh I understand now that this is happening because APIKit is using universal target. I'd like to address this at the upstream.

**Comment by ikesyo** [comment]
This should be good now. ✨

**Comment by ishkawa** [comment]
👍

**Pull request merged**
