### PR TITLE
Set version 4.1.0

### PR DESCRIPTION
**Pull request by ishkawa**

### CODE REVIEW

**Comment by ikesyo** [comment]
I'll proceed this!

**Comment by ikesyo** [comment]
Just release 4.1.0: https://github.com/ishkawa/APIKit/releases/tag/4.1.0

@ishkawa Could you please publish to CocoaPods or make me as the podspec owner (then I'll take care of pushing)?

**Comment by ishkawa** [comment]
@ikesyo Thank you for the work! I have just added you as an owner of this pod.

**Comment by ikesyo** [comment]
Done 🎉 

```
$ pod trunk push

[!] Found podspec `APIKit.podspec`
 Updating spec repo `master`
Validating podspec
 -> APIKit (4.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  APIKit (4.1.0) successfully published
 📅  April 9th, 14:11
 🌎  https://cocoapods.org/pods/APIKit
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Pull request merged**
