### PR TITLE
Avoid parsing when status is 204.

### PR DESCRIPTION
**Pull request by pocket7878**
Some API returns 204 and it make a parse error.
So avoid call responseBodyParser and passing dummy data to responseFromObject.

### CODE REVIEW

**Comment by pocket7878** [comment]
After sending this PR I began feeling it is better to handle 204 on responseBodyParser by passing status code to parseData...
Would you let me know what your thoughts are on this matter?

**Comment by ishkawa** [comment]
Passing dummy data to response body parser is a little bit weird for me. Ideally, `API` should return the result without using response body parser when it receives 204. If `T.Response` is a `Optional`, the result should be `Result.Success(value: T.Response.None)`, otherwise `Result.Failure(error: NSError(...))`.

The former is still acceptable for me if the latter can't be implemented in current version of Swift :wink:

**Comment by ishkawa** [comment]
I noticed response body may be empty regardless of status code, so response body parser have to handle empty data correctly. How about change `ResponseBodyParser.JSON` to return `[:]` if length of `NSData` is 0?

```swift
public func parseData(data: NSData) -> Result<AnyObject, NSError> {
    switch self {
    case .JSON(let readingOptions):
        if data.length == 0 {
            return .success([:])
        }

        return try { error in
            return NSJSONSerialization.JSONObjectWithData(data, options: readingOptions, error: error)
        }
    ...
    }
}
```

**Comment by ishkawa** [comment]
Thank you :+1:

**Pull request merged**
