### PR TITLE
[RFC] Style: Early termination instead of using var

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ishkawa** [comment]
Nice code 🎉

PS I intend to add you as a collaborator. Will you accept this?

**Comment by ikesyo** [comment]
:wink: 

I would be happy to accept it :sparkles:

**Comment by ishkawa** [comment]
I have just added you as a collaborator. Now you can develop on this repository. From now on, I will send pull request to make any change on this repository.

**Comment by ikesyo** [comment]
Thank you for adding! I'd be making efforts.

**Pull request merged**
