### PR TITLE
Simplify project structure

### PR DESCRIPTION
**Pull request by ishkawa**
We adopted xcworkspace so that developers who support iOS 7 can install APIKit via git submodule. It was necessary at that time, but now we dropped iOS 7 support so we don't have to use xcworkspace.

### CODE REVIEW

**Comment by ikesyo** [comment]
IIRC the workspace-based structure is adopted by #44, that is not related to iOS 7 support (although the request was come from #40). Not using workspace means dropping the installation option using git submodule against https://github.com/ishkawa/APIKit/issues/40#issuecomment-108680317, not dropping completely iOS 7 support.

> BTW, as @sagaraya suggested, we should also provide installation using git submodule. I will try to make Xcode project independent of Carthage in a few days.

**Comment by ikesyo** [comment]
One more point: [Using the built (custom) framework requires workspace](https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/ImportingaFrameworkIntoaPlayground.html).

**Comment by ishkawa** [comment]
I've completely forgotten iOS8+ git submodule installation! Apparently, we should support it :bow:

**Comment by ishkawa** [comment]
I'll send PR that enables Travis CI.

**Comment by ikesyo** [comment]
:+1:

**Pull request closed without merging**
