### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by ikesyo**
~~Depends on #193.~~ ✅ 

We should audit the APIs to match with Swift 3 API Design Guidelines.

### CODE REVIEW

**Comment by MarvinNazari** [comment]
@ikesyo is this updated to the latest beta?

**Comment by MarvinNazari** [comment]
Hi @ikesyo, shouldn't we rename `interceptURLRequest` and  `interceptObject` too like you did `responseFromObject`?
what about change enum cases to lowercase too maybe?
I would love to help! if there is anything i can do!

**Comment by MarvinNazari** [comment]
the Xcode 8 is out, can we merge this @ikesyo @ishkawa?

**Comment by ishkawa** [comment]
@ikesyo Thank you for the great work 👍 👍 👍 

I have some suggestions that would improve smoothness with Swift 3 APIs.

### Omit `Type` suffix of some protocols

According to the [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/), "Protocols that describe what something is should read as nouns (e.g. Collection)." `RequestType`, `BodyParametersType`, `DataParserType` and `SessionAdapterType` seem to satisfy this condition.

### Rename `sendRequest(_:handler:)` to `send(_:handler:)`

IMO, the word "request" can be omitted because it is implied when we send something from Session.

### Rename `cancelRequest(_:passingTest:)` to `cancelRequests(withType:passingTest:)`

Unlike the sending method, canceling method treats multiple requests. I think we should imply we may cancel multiple requests, so the word "requests" should be exposed in method name. In addition, `withType` label is necessary because the type of the first parameter is not explicit in this context.

**Comment by ishkawa** [comment]
After we resolve renaming, I will merge this PR and release 3.0 ✨

**Comment by ikesyo** [comment]
The renaming is finished. ✨

**Comment by ishkawa** [comment]
🎉

**Pull request merged**
