### PR TITLE
Faster CI build

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
It's ready now. :zap:

**Comment by ishkawa** [comment]
:+1:

**Comment by ishkawa** [comment]
Oh, CI fails in `carthage bootstrap`.

**Comment by ishkawa** [comment]
`carthage build --no-skip-current`, not `carthage bootstrap`.

**Comment by ikesyo** [comment]
@ishkawa It seems that [upgrading dependencies](https://github.com/ishkawa/APIKit/commit/486d4adbfdc4ff43d03ba98552bad939ed518bcd) fixed the issue. :trollface:

**Comment by ishkawa** [comment]
Thank you :sparkles:

**Pull request merged**
